pool:
  vmImage: windows-2019

steps:

# Install DotNet Core 2.x
# Required by GitVersion tool
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops
- task: UseDotNet@2
  displayName: 'Install DotNet Core 2.x'
  inputs:
    packageType: runtime
    version: 2.x

# Install DotNet Core SDK 3.1.x
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops
- task: UseDotNet@2
  displayName: 'Install DotNet Core SDK 3.1.x'
  inputs:
    packageType: sdk
    version: 3.1.x

# Run GitVersion Tool
# https://gitversion.net/docs/build-server-support/build-server/azure-devops
- task: GitVersion@5
  enabled: true
  displayName: 'Run GitVersion Tool'
  inputs:
    runtime: core
    configFilePath: gitversion.yml

# Set Manifest Version Information
# Modify the csproj file directly and use values calculated by the GitVersion tool
# https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Attributes
- task: Assembly-Info-NetCore@2
  enabled: true
  displayName: 'Set Manifest Version Information'
  inputs:
    FileNames: 'PlexCleaner/PlexCleaner.csproj'
    VersionNumber: $(GitVersion.AssemblySemVer)
    FileVersionNumber: $(GitVersion.AssemblySemFileVer)
    InformationalVersion: $(GitVersion.InformationalVersion)
    PackageVersion: $(GitVersion.InformationalVersion)
    #LogLevel: verbose

# DotNetCore Publish
- task: DotNetCoreCLI@2
  displayName: 'DotNetCore Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    #configuration appears to be ignored, use commandline instead
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false

# 7-Zip Build Output
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops
- task: ArchiveFiles@2
  displayName: '7-Zip Build Output'
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    includeRootFolder: false
    archiveType: 7z
    archiveFile: '$(Build.ArtifactStagingDirectory)/PlexCleaner.7z'
    replaceExistingArchive: true

# Release to GitHub
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops
- task: GitHubRelease@1
  displayName: 'Release to GitHub'
  inputs:
    gitHubConnection: 'github.com_ptr727'
    repositoryName: $(Build.Repository.Name)
    action: create
    target: $(Build.SourceVersion)
    tagSource: userSpecifiedTag
    tag: $(GitVersion.NuGetVersion)
    title: $(GitVersion.NuGetVersion)
    assets: '$(Build.ArtifactStagingDirectory)/PlexCleaner.7z'
